{% set name = "functime" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/functime-org/functime/archive/v{{ version }}.tar.gz
  sha256: 825ab23683394790fbca7c27267d01b0ea8f645ccfcfda6b78ba71d48ae21a93

build:
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin <2,>=1.2.1
    - pip
  run:
    - python
    - cloudpickle
    - flaml <3,>=2.0.2
    - holidays
    - numpy
    - polars >=0.20.7
    - scikit-learn <2,>=1.2.2
    - scipy
    - tqdm
    - typing-extensions  # [py<310]


test:
  imports:
    - functime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/functime-org/functime
  doc_url: https://docs.functime.ai/
  summary: Time-series machine learning at scale.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
